---
version: '2'
services:
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"    
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: 172.31.6.147:2888:3888;172.31.8.126:2888:3888
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"    
    depends_on:
      - zookeeper-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 172.31.6.147:2181,172.31.8.126:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.31.8.126:9092
    extra_hosts:
      - "moby:127.0.0.1"